### ISSUE TITLE
Missing documentation on how to define jobs

### ISSUE THREAD

**Issue by ArturMoczulski** [agenda/agenda-rest#101]
For the life of mine I can not figure out how to use the `POST /job` endpoint to define a job or load my already defined jobs into the `agenda-rest` instance.

I've spent about four hours reading the documentation and reading through the source code and I completely do not understand how to use this endpoint.

In the docs it says the endpoint takes a `url`, but I have no idea what should be under that URL and in what format. How do I provide the JS source code of my job? Or am I getting this completely wrong?

Also, I'd love to preload my jobs from source instead of having to define them with endpoints. Is this possible with this library?

This essentially stops me from using the library because I do not know how to define jobs and the documentation is as helpful as saying: `url`. I don't even know what that means.

After reading the source code I can see that the only thing that is being done in `defineJob` is just making a HTTP request to the `url` and then calling a callback. I don't understand where the my source code of my job supposed to be taken from.

Please help and I suggest to add much more instructions on how to define a job which is de facto the first endpoint you want to deal with when trying to use this library.

This is a shame as I would love to use it - the rest seems great. But until I get some answers I will have to rely on a custom written simple express www server with pure `agenda`.

I'm happy to produce documentation content if maintainers would explain how to use this endpoint.

**Comment by 2bigO** [comment]
@ArturMoczulski the `url` is for jobs that themselves reside in HTTP endpoints, a GET/POST/PUT/... request from, e.g. an email service where you want to send out an email in a specific time.

If you want to invoke some js code which you have access to, pure `agenda` is actually the right way to do so. In a hybrid use case (some your own code, some services) you can serve your code as HTTP endpoints using something like `expressjs` and have `agenda-rest` call them.

**Comment by ArturMoczulski** [comment]
Got it.

So I take the JS code for my jobs does not have to be any `agenda`-specific code, as `agenda-rest` already utilizes `agenda` to take care of the scheduling. Seems like I should just expose my actual job logic as plain rest endpoints that could be completely non-`agenda`.

I am getting this right? 

What got me confused was seeing that `agenda-rest` already instantiates `agenda` in itself so job definitions should be passed to it somehow (the actual JS code).

If I'm getting this right, if I expose the following logic at an endpoint:

```
// This is mostly pseudo-code ;)
app.post('/writer', () => {
  fs.writeFile('foo.txt', Math.random());
});
```

Calling `GET /writer` should do the file writing work.

And since `agenda-rest` utilizes `agenda`'s scheduling, I can set up a job there to call this endpoint on a schedule.

Correct?

**Comment by 2bigO** [comment]
@ArturMoczulski exactly, you got it.

**Comment by ArturMoczulski** [comment]
Thanks for taking the time to explain.

I'll try to find 30-60 minutes in the next couple of days to prepare a documentation with a solid example of this once I get it to work 👍

**Comment by ArturMoczulski** [comment]
f
