### ISSUE TITLE
got 404,why

### ISSUE THREAD

**Issue by bulolo** [agenda/agenda-rest#105]
![image](https://user-images.githubusercontent.com/10026498/106323479-73b6e980-62b2-11eb-9c78-15f71a4836db.png)

**Comment by the-vampiire** [comment]
i am having the same issue. did you figure this out @bulolo?

**Comment by the-vampiire** [comment]
ahh `root` must be set to `HOST:PORT/api`!

ex: `localhost:4040/api/job`
