### ISSUE TITLE
How to repeat job at Friday at 5am for every week

### ISSUE THREAD

**Issue by hbinduni** [agenda/agenda-rest#162]
Hi, using `agendash`, i can configure `job` like this:

<img width="492" alt="agendash repeat job every week" src="https://user-images.githubusercontent.com/1378410/117583608-43dd7480-b132-11eb-8a45-c121db69f5b5.png">

how can i do the same using `/api/job/every`?
i am trying something like this:

```
{
    "name": "do-something",
    "interval": "At 05:00 on Friday",
    "data": {"name": "Your metadata goes here..."}
}
```

but it seem not schedule correctly.

**Comment by ccovarrubias** [comment]
Have you tried with cron syntax? Here you can write your expression with live preview https://crontab.guru/
Yours could be "0 5 * * 5".

Don't try the old syntax with "?", agenda only recognizes (*),(-),(/), (,).

Hope it helps.

**Comment by hbinduni** [comment]
thank you @ccovarrubias it work great
