### ISSUE TITLE
Adding Jobs Returns Duplicate ObjectID

### ISSUE THREAD

**Issue by ia-josephp** [agenda/agenda-rest#17]
Hey there. We are experiencing some strange behavior and we are unsure if it is our own fault from lack of understanding or something to do with agenda-rest. 

Error:

WriteError({"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: agenda.jobDefinitions index: _id_ dup key: { : ObjectId('5afc675a3f77ac1f5715b6ba') }","op":{"name":"test111","url":"192.168.1.17:1880/relayon","method":"POST","_id":"5afc675a3f77ac1f5715b6ba"}})

What happens?

We start agenda-rest.
We submit a job.
We verify the job in jobDefinitions. It is there.
We submit another job. 
We receive a duplicate ID warning. 
We restart agenda-rest.
We submit a job, it works. 
We submit again, returns duplicate ID error.

Whenever the first job is submitted, it becomes the only ObjectID that is attempted to be used while agenda-rest is running. Inserting directly to MongoDB works just fine. 

Regards

**Comment by 2bigO** [comment]
Hi @eaf-josephportello 

Sorry for the delay in response, traveling.

I've just replicated this error. The fault is in the `agenda-rest` code, working on it.

Thanks for reporting!

**Comment by 2bigO** [comment]
@eaf-josephportello 

I just tested this with `agenda-rest@0.7.5` that I just pushed and it seems to be resolved.

You'll need to update:

```sh
sudo npm update -g agenda-rest
```

Please feel free to reopen if the issue persisted.

Thanks again 🎉
