### ISSUE TITLE
define vs jobs

### ISSUE THREAD

**Issue by rogueturnip** [agenda/agenda-rest#2]
Hi!

I wanted to ask a question about the implementation just to understand the logic.  The API /api/new creates a definition of a job and the callback and then /api/every or /api/schedule creates the jobs.  I was wondering what the reason was not to just create the definition at the same time as the job is created?  Why did you decide to create a table of definitions?

Thanks!

Tony

**Comment by 2bigO** [comment]
Hi Tony,

`agenda-rest` is just a wrapper around [`agenda`](https://github.com/agenda/agenda), the amazing and widely popular scheduler by @rschmukler.

I guess the reason for this design decision is to be able to delete all jobs of a specific "type" (denoted by name) via the delete operation.

Also, one could get decent analytics grouped by name, e.g. using the [`agendash`](https://github.com/agenda/agendash) dashboard.

**Comment by rogueturnip** [comment]
Great thanks!  It's a really nice wrapper!  What I initially was confused with is I thought that /api/new created a generic definition that I could then create jobs of different names to use but that wasn't the case.  The name of the job has to match the name of the definition.

My use case was to create a generic call to an API in the definition and then jobs to call it for different processess with different data.  I would then name the jobs "jobname@definition".  Where I ran into problems was you can only have a single "every" job setup. 

What I'm considering doing to get around this create a generic definition for the API call and then in the jobs put in the data a "ID" field that describes who is making the call.  The "every" function I'll then change to do job specific creation (job.create().repeatEvery().save()) to allow for multiple jobs with the same definition name.

Does that make sense?

Thanks!

**Comment by 2bigO** [comment]
> Where I ran into problems was you can only have a single "every" job setup.

I didn't know that was the case, the solution you proposed seems to work, but would be a hack. Can you check whether this restriction holds in upstream (latest agenda), if not I should update agenda's version to latest, if so, can you think of a better way to resolve it in `agenda-rest`'s code? I could cook up the solution that you arrive at in a few days, or even better, code it yourself and submit a PR.

**Comment by rogueturnip** [comment]
I checked out the agenda issues and it's something that's liked as a feature request to allow for "single" to be set in the every call but right now it's a restriction.

I'll do the changes myself, I've been doing a lot of modifications, adding in apis that allow viewing of the definitions and jobs, removing jobs or definitions, and also schedule that repeats daily at a certain time or a scheduled event that occurs once.

**Comment by 2bigO** [comment]
> I've been doing a lot of modifications, adding in apis that allow viewing of the definitions and jobs, removing jobs or definitions, and also schedule that repeats daily at a certain time or a scheduled event that occurs once.

Super cool, if you felt these additions would be of use to others, I'd very much appreciate if you could share them as a pull request here.
