### ISSUE TITLE
Agenda v2.0.0

### ISSUE THREAD

**Issue by simison** [agenda/agenda-rest#20]
Agenda v2.0.0 is out now.

We should test and make sure this library works with it. :-)

If and when it does, we could add this to the feature comparison chart: https://github.com/agenda/agenda#feature-comparison

**Comment by 2bigO** [comment]
Right. I will make `agenda-rest` compatible with version 2.0 during next week. Good job 👍

**Comment by OmgImAlexis** [comment]
Shall we bump this to `v2.0.0` to coincide with Agenda?

**Comment by simison** [comment]
Yeah, I guess we need a major version bump. Suppose the API of `agenda-rest
` won't have breaking changes but folks might need upgrading since Agenda v2 has changed Node.js & MongoDB version requirements.

The next major version is `1.0.0` — in my opinion that's okay, bumping up to `2.0.0` might just confuse. I don't think we should start following Agenda's versions for this package — better stick to semver practices. What do you think?

**Comment by OmgImAlexis** [comment]
I'm open for anything as long as we keep to it.

**Comment by 2bigO** [comment]
I cooked an initial draft at #21. The impeding problem I'm facing now is that the `processor` for `agenda.define` does not get invoked. There is no signature change for `agenda.define` in `v2.0.0`, right? Any suggestions? I'm on `mongo@3.6.4`, does this matter?

UPDATE: This was not the issue, had bad code in `define` body

**Comment by 2bigO** [comment]
Done. @OmgImAlexis appreciate if you merge when you reviewed 🚀 let me know if anything needs changing before the merge

**Comment by 2bigO** [comment]
I just published `agenda-rest@1.0.1` to npm. Can this be closed now or is there anything else @simison?

**Comment by simison** [comment]
Perfect! Thanks for working on it; this can be closed. 👍
