### ISSUE TITLE
POST /api/job/cancel API cancels a job only when "name" is submitted

### ISSUE THREAD

**Issue by Mr-Sharma** [agenda/agenda-rest#22]
The above API cancels a job based on  **name** only. Can we cancel a job based on **_id** or using properties of **job.data**  like in agenda?

**Comment by 2bigO** [comment]
The code passes POST data directly to the cancel method of agenda, which accepts a mongo query. Do you get an error without submitting the name? Can you paste the error here?

**Comment by Mr-Sharma** [comment]
There is no error as such. It just says 0 jobs cancelled.

**Comment by 2bigO** [comment]
I was able to reproduce the issue, thanks for reporting @Mr-Sharma, this will be resolved in the upcoming `v1.0.1`, i.e. when #21 is merged. Thanks again.

**Comment by 2bigO** [comment]
@Mr-Sharma this should be resolved by updating to `v1.0.1` which I just published. Appreciate if you could test and confirm 👍  Feel free to reopen if the issue persisted.
