### ISSUE TITLE
CTRL+C does not work

### ISSUE THREAD

**Issue by 2bigO** [agenda/agenda-rest#26]
The [graceful shutdown code](https://github.com/agenda/agenda-rest/blob/master/cli.js#L24) does not reach [process exit](https://github.com/agenda/agenda-rest/blob/master/cli.js#L29), hence the app remains open.

**Comment by darrenbrett** [comment]
Same thing with "COMMAND + C" on a Mac.

**Comment by sampathBlam** [comment]
@darrenbrett : Kindly verify if the issue still exists. A fix for this has been pushed to the master. If it works fine, then we can ask the maintainers to close the issue.

**Comment by sampathBlam** [comment]
@keyvan-m-sadeghi : Can this issue be closed?

**Comment by 2bigO** [comment]
Sure @sampathBlam, I'll publish a new version today and then close the issue.

**Comment by 2bigO** [comment]
This issue appears to be resolved in the latest release.
