### ISSUE TITLE
Wanna join the gang?

### ISSUE THREAD

**Issue by simison** [agenda/agenda-rest#3]
Hello @keyvan-m-sadeghi 👋 

You've done some impressive work here! :thumbsup: :thumbsup:

We're working on Agenda and [Agendash](https://github.com/agenda/agendash) — latter one has built-in API like yours. It would be awesome if the API would be separate (like your package), somewhat "official" and Agendash could use that then instead.

What do you think? Would you be interested helping out with such project? :-) We could move this package to @Agenda org and it would get more attention from the awesome Agenda community.

We have [Slack channel](https://slackin-ekwifvcwbr.now.sh/) if you wanna join and discuss this more. :-)

Have a good one!

**Comment by simison** [comment]
Pinging @naterkane here as well, because of similar but a bit older package https://github.com/naterkane/rest-scheduler :-)

**Comment by 2bigO** [comment]
Hi @simison 🖐️
Sure, sounds like a great idea. We can start with moving this repo to @agenda, then I can apply the changes needed for Agendash to use this package if someone directs me how in an issue.

**Comment by 2bigO** [comment]
I just tried to transfer the ownership, seems it needs a permission.
![screenshot_20180201-140319](https://user-images.githubusercontent.com/1758649/35674159-0209e4ca-0759-11e8-8b68-22572c804ef0.jpg)

**Comment by OmgImAlexis** [comment]
Could you transfer it to one of us and we can the move it?

**Comment by simison** [comment]
> Sure, sounds like a great idea. We can start with moving this repo to @agenda, then I can apply the changes needed for Agendash to use this package if someone directs me how in an issue.

This is awesome! :tada:

>Could you transfer it to one of us and we can the move it?

I'll just add @keyvan-m-sadeghi to org and we can move it directly to @Agenda then. (Update: done, check email or visit org site)

**Comment by 2bigO** [comment]
Done

**Comment by naterkane** [comment]
I have some updates to the rest-scheduler that I'm not sure ever got pushed. Haven't looked at it in about 18 months though iirc.

**Comment by simison** [comment]
@naterkane yup! would be great if you can have a look at this repo (now transferred to `/agenda/agenda-rest`) to see if there's something in your work that could be brought over to there — for joint effort! 💪 

I picked _this_ repository initially for @Agenda because had more recent work than yours. ;-) No hard feelings.

**Comment by naterkane** [comment]
I'm not offended. The one I put together had a specific strategy. Send ANY
payload to a url, at a given time. I used it to fire payloads to rest
endpoints within a large, complicated SoA application.. our implementation
ended up not using Mongo, but something that could provide atomicity at
scale and use less resources.

**Comment by simison** [comment]
Great! :-)
