### ISSUE TITLE
Choose HTTP client

### ISSUE THREAD

**Issue by 2bigO** [agenda/agenda-rest#6]
Is it a good idea to use [`axios`](https://github.com/axios/axios) in place of `request-promise`?

**Comment by simison** [comment]
I'd say the one who works on it gets to choose. ;-)

**Comment by OmgImAlexis** [comment]
I'd suggest [Frisbee](https://github.com/niftylettuce/frisbee) it's based on fetch and I use it throughout my other projects without any issues.

**Comment by 2bigO** [comment]
@OmgImAlexis Frisbee looks very nice! Thanks for suggestion. I'll wait to see what requirements we have from Agendash then come back to this while integrating those changes. Thanks again. Closing for now.
