### ISSUE TITLE
Provide information about the CLI arguments in the documentation

### ISSUE THREAD

**Issue by sampathBlam** [agenda/agenda-rest#61]
Do you guys think if we need information about the command line arguments that we give to agenda-rest, in the documentation? At this point, we can get to know about them only by having a look at cli.js. Let me know if this makes sense. I can work on a PR for that.

**Comment by 2bigO** [comment]
Doesn't `agenda-rest --help` already do this? If so, I guess it's worth mentioning in the readme,

**Comment by 2bigO** [comment]
I totally agree with having a dedicated CLI section in the readme. Help is always appreciated 🎉

**Comment by sampathBlam** [comment]
Great ! I will work on it. Thanks.
