### ISSUE TITLE
Allow options as a parameter when creating jobs.

### ISSUE THREAD

**Issue by geosp** [agenda/agenda-rest#72]
Is there a reason why we don't have options as a parameter at the same level of `interval`, `name`, and `data`?  May I implement this feature?

**Comment by geosp** [comment]
The options I'm referring to are here https://github.com/agenda/agenda#creating-jobs

**Comment by 2bigO** [comment]
I think the reason is that `options` was introduced after the initial version of `agenda-rest`!

> May I implement this feature?

Definitely, appreciated!

**Comment by geosp** [comment]
@keyvan-m-sadeghi Thank you. The PR is in. My reason for needing this feature is to specify the timezone for my event.
